name: jira integration

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache node_modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Pull request
      if: ${{ github.event_name == 'pull_request' }}
      env:
        STEP: "CODE_REVIEW"
        GITHUB: ${{ toJson(github) }}
        JIRA_USER: ${{ secrets.JIRA_USER }}
        JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
      run: |
        yarn
        node jira-integration.js

    - name: Merge
      if: ${{ github.event_name == 'push' }}
      env:
        STEP: "MERGE"
        GITHUB: ${{ toJson(github) }}
        JIRA_USER: ${{ secrets.JIRA_USER }}
        JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
      run: |
        yarn
        node jira-integration.js
